
# "service" is the name of this project. This will also be added to your AWS resource names.
service: example-serverless

package:
  individually: true

custom:
  esbuild:
    exclude:
      - "aws-sdk"

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: 
        Fn::GetAtt:
            - database
            - Arn
functions:
  getPosts:
    handler: src/Post/handlers/getPosts.main
    events:
      - httpApi:
          path: /posts
          method: get
  createPost:
    handler: src/Post/handlers/createPost.main
    events:
      - httpApi:
          path: /posts
          method: post

resources: # CloudFormation template syntax from here on.
  Resources:
    database:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: example-blog-app
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1