export { Body } from './body.decorator'
export { Query } from './query.decorator'
export { Inject } from './inject.decorator'
export { Lambda } from './lambda.decorator'
export { Param } from './param.decorator'
export { Service } from './service.decorator'
export { Event } from './event.decorator'
export { Returns } from './returns.decorator'
